# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/veilarbdialog
team: oppfolging
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
webproxy: true
healthcheck:
  liveness:
    path: veilarbdialog/internal/isAlive
    initialDelay: 60
  readiness:
    path: veilarbdialog/internal/isReady
    initialDay: 60
prometheus:
  enabled: true
  path: veilarbdialog/internal/metrics
resources:
  limits:
    cpu: 2
    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 512Mi
fasitResources:
  used:
  - alias: loadbalancer:veilarbdialog
    resourceType: loadbalancerconfig
  - alias: veilarbdialogDataSource
    resourceType: datasource
  - alias: srvveilarbdialog # mapToProperty="systembruker"
    resourceType: credential
  - alias: appdynamics
    resourceType: applicationproperties
  - alias: veilarbdialog.properties
    resourceType: applicationproperties
  - alias: securityTokenService
    resourceType: baseUrl
  - alias: abac.pdp.endpoint # mapToProperty="abac.endpoint"
    resourceType: restservice
  - alias: Aktoer_v2 # mapToProperty="aktoer.endpoint"
    resourceType: webserviceendpoint
  - alias: veilArbOppfolgingAPI # mapToProperty="veilarboppfolging.api"
    resourceType: restservice
  - alias: unleash-api # mapToProperty="unleash"
    resourceType: restservice
  - alias: aktivitetsplan
    resourceType: baseurl

  # ISSO
  - alias: isso-host
    resourceType: baseurl
  - alias: isso-jwks
    resourceType: baseurl
  - alias: isso-issuer
    resourceType: baseurl
  - alias: isso.isalive
    resourceType: baseurl
  - alias: isso-rp-user
    resourceType: credential
  - alias: veilarblogin.redirect-url # mapToProperty="oidc-redirect"
    resourceType: restservice
  - alias: aad_b2c_clientid
    resourceType: credential
  - alias: veilarbazureadproxy_discovery # mapToProperty="aad_b2c_discovery"
    resourceType: restservice

  # Queue
  - alias: mqGateway03
    resourceType: queuemanager

  - alias: VARSELPRODUKSJON.VARSLINGER
    resourceType: queue
  - alias: VARSELPRODUKSJON.BEST_VARSEL_M_HANDLING
    resourceType: queue
  - alias: VARSELPRODUKSJON.STOPP_VARSEL_UTSENDING
    resourceType: queue
  - alias: henvendelse_OPPGAVE.HENVENDELSE
    resourceType: queue

  exposed:
  - alias: veilarbdialogAPI
    resourceType: restservice
    path: /veilarbdialog/api
